// socket
export const WS_OPEN = 'SOCKET_ONOPEN'
export const WS_CLOSE = 'SOCKET_ONCLOSE'
export const WS_ERROR = 'SOCKET_ONERROR'
export const WS_MESSAGE = 'SOCKET_ONMESSAGE'

// poker
export const SELECT_POKER = 'SELECT_POKER'
export const SELECT_CHIP = 'SELECT_CHIP'
export const RESET_POINTS = 'RESET_POINTS'
export const SET_SELF_ITEM_POINTS = 'SET_SELF_ITEM_POINTS'
export const SUM_POINTS = 'SUM_POINTS'
export const SET_SUM_ITEM_POINTS = 'SET_SUM_ITEM_POINTS'

export const SET_POKER_WIDTH = 'SET_POKER_WIDTH'
export const SET_POKER_HEIGHT = 'SET_POKER_HEIGHT'
export const SET_POKER_COORD = 'SET_POKER_COORD'

export const SET_CHIP_WIDTH = 'SET_CHIP_WIDTH'
export const SET_CHIP_HEIGHT = 'SET_CHIP_HEIGHT'
export const APPEND_CHIP_COORD = 'APPEND_CHIP_COORD'

// set bet role from server
export const SET_BET_POKER_FROM_SERVER = 'SET_BET_POKER_FROM_SERVER'
export const SET_BET_CHIP_FROM_SERVER = 'SET_BET_CHIP_FROM_SERVER'
export const UPDATE_CHIP_LIST = 'UPDATE_CHIP_LIST'

// user
export const USER_SET_GAMEID = 'USER_SET_GAMEID'
export const USER_SET_UID = 'USER_SET_UID'
export const USER_SET_RID = 'USER_SET_RID'

// modal
export const OPEN_MODAL_TIP = 'OPEN_MODAL_TIP'
export const CLOSE_MODAL_TIP = 'CLOSE_MODAL_TIP'
export const SET_MODAL_TIP_TEXT = 'SET_MODAL_TIP_TEXT'
export const OPEN_MODAL_ALERT = 'OPEN_MODAL_ALERT'
export const CLOSE_MODAL_ALERT = 'CLOSE_MODAL_ALERT'
export const OPEN_MODAL_ALERT_MASK = 'OPEN_MODAL_ALERT_MASK'
export const CLOSE_MODAL_ALERT_MASK = 'CLOSE_MODAL_ALERT_MASK'
export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'

// game
export const SET_GAME_STATUS = 'SET_GAME_STATUS'
export const START_GAME = 'START_GAME'
export const END_GAME = 'END_GAME'
export const INIT_GAME = 'INIT_GAME'
export const CREATED = 'CREATED'
export const SET_WINNER = 'SET_WINNER'
export const SET_POINT = 'SET_POINT'
export const START_HEART_BEAT = 'START_HEART_BEAT'
export const STOP_HEART_BEAT = 'STOP_HEART_BEAT'
export const HEART_BEAT_DISCONNECTED_COUNT = 'HEART_BEAT_DISCONNECTED_COUNT'
